language: node_js
script:
  - "npm run travis"
  - "npm run browserify:tests"
  - "node_modules/karma/bin/karma start tests/karma-sauce.conf.js --browsers FIREFOX_V4,FIREFOX_V11,FIREFOX_V20,FIREFOX_V35"
  - "node_modules/karma/bin/karma start tests/karma-sauce.conf.js --browsers CHROME_V35,CHROME_V40,ANDROID_V4.0,ANDROID_V4.3"
  - "node_modules/karma/bin/karma start tests/karma-sauce.conf.js --browsers INTERNET_EXPLORER_V9,INTERNET_EXPLORER_V10,INTERNET_EXPLORER_V11"
node_js:
  - "0.10"
env:
  - secure: "fzJQ0VYZev8+VZSyCnUbHUhWpmA6369yQMeVeVIIYL//4opHd+eSd1nmjH5l5b2ZxwUN1QtzGXdZiF+sCJH/wOt0ykRzLez/ogcjwG/rNcNdXQypio5w+oVxBcDNEWBMYyrZrEnuccYVacQKIXam6Def4n5NiTN0ojyoPVII53A="
  