language: node_js
script:
  - "npm run travis"
  - "npm run browserify:tests"
  - "node_modules/karma/bin/karma start tests/karma-sauce.conf.js --browsers FIREFOX_V4,FIREFOX_V11,FIREFOX_V20,FIREFOX_V35"
  - "node_modules/karma/bin/karma start tests/karma-sauce.conf.js --browsers CHROME_V35,CHROME_V40,ANDROID_V4.0,ANDROID_V4.3"
  - "node_modules/karma/bin/karma start tests/karma-sauce.conf.js --browsers INTERNET_EXPLORER_V9,INTERNET_EXPLORER_V10,INTERNET_EXPLORER_V11"
node_js:
  - "0.10"
env:
  # SAUCE_USERNAME=...
  - secure: "gHcd43f/5i2nSuVXMr9YjmSZkdM9Qiq8f2qNAtoNGEW9yIKQutSMSDA33WPRIk5ibHnKyVes5Lt2IwZnlAvrVMjSoE7Vn7uHA84fBtuaWoajQn7ckVSN6IvNGCV2p5uZ9sL7JwoqhprMvYnempn+GBMimXCYpmr45/N5wBz6Oq8="
  # SAUCE_ACCESS_KEY=...
  - secure: "gSXfR+VSveAVCAZlK90sVEP77KDX9B9gxXvXnobkykvqaaWTkmlTBtPOIvSBMIc+VXkwfTA5/8b/zaBqZB8LGcQCjoyLh4M1xLcki3iAAWPu9xLiiDEE3MVpST8Ml2+4bPDuzHlQt26u2QtoN7kn5/H9O5NYy6pW5HZAiWVUTnY="
